### ISSUE TITLE
Gamebatte_watchOS 12 Issues

### ISSUE THREAD

**Issue by Y3H801** [gabrieloc/GIOVANNI#10]
<img width="257" alt="screen shot 2017-03-22 at 7 24 14 pm" src="https://cloud.githubusercontent.com/assets/15676718/24226618/7148d0fc-0f35-11e7-863f-cbe3f2ff152f.png">

**Comment by gabrieloc** [comment]
Duplicate of https://github.com/gabrieloc/GIOVANNI/issues/3

**Comment by Y3H801** [comment]
Sorry about that
