### ISSUE TITLE
Dependency Analysis Error

### ISSUE THREAD

**Issue by Y3H801** [gabrieloc/GIOVANNI#12]
I followed the entire redmondpie instructions and recieved these errors after compiling
<img width="1060" alt="screen shot 2017-03-23 at 5 07 40 pm" src="https://cloud.githubusercontent.com/assets/15676718/24272445/69792ee2-0feb-11e7-94c5-e9fad84beafe.png">

**Comment by gabrieloc** [comment]
Change the bundle id for the iOS, watchOS, and watchOS extension to something unique.

**Comment by Y3H801** [comment]
oh yeah my bad, i completly forgot to change it for all of them, i only changed it for the main, I'll try that when I get off work, thanks for helping!

**Comment by Y3H801** [comment]
I did what you said and it fixed the issues but resulted in one more issue: 
<img width="799" alt="screen shot 2017-03-24 at 4 30 34 pm" src="https://cloud.githubusercontent.com/assets/15676718/24314393/516c8762-10af-11e7-990f-9f47b88743cd.png">

My iPhone is running 10.2 and I have set the deployment target to 10.2 and my Apple Watch is on 3.1.3 and have set all three deployment targets to 3.1.3

**Comment by gabrieloc** [comment]
The error literally tells you what to do.

**Comment by Y3H801** [comment]
yeah my bad im stupid, its all fixed sorry for wasting your time

**Comment by gabrieloc** [comment]
Not calling you stupid, just appreciate some effort 👍

**Comment by Y3H801** [comment]
no i was calling myself stupid lmao, i gave up too quickly it was completely my bad and im just frustrated because I have used Xcode in a while

**Comment by vicorx** [comment]
i still dont now what to do

**Comment by burntscarr** [comment]
@vicorx
If you need help my discord username is burntscarr#4595
Or on Twitter I am burntscarr. Please message me and I’ll do my best to help. Once I get everything working perfectly I’ll release my own fork of this github project.

**Comment by vicorx** [comment]
@burntscarr hi I sent u a friend request on discord, vchn7#0622
