### ISSUE TITLE
Problem With App Installation

### ISSUE THREAD

**Issue by xTcR** [gabrieloc/GIOVANNI#13]
Hello everyone, recently saw this project and thought it would be cool to try out but recently whilst trying to build and run the app I got this error (shown in the picture), I tried to search the internet for a fix or answer to this problem but alas I was left without a result, if someone could help me that would be awesome!

My Bundle Identifiers: (for the place where it says [myname], I did not actually put that, I put my name but do not want to share that info <3
iOS: com.[myname].giovanni
WatchOS: com.[myname].giovanni
Watchkit Extension: com.[myname].giovanni
Gambatte: com.[myname].gambatte

NSExtension
WKAppBundleIdentifier: com.[myname].giovanni
NSExtensionPointIdentifier: com.apple.watchkit
Thank You!
<img width="420" alt="screen shot 2017-03-24 at 8 07 28 pm" src="https://cloud.githubusercontent.com/assets/26663709/24318216/aa49aa34-10cf-11e7-8bb5-47b09cfa08ab.png">

**Comment by ghost** [comment]
I found if I changed the Bundle Identifiers to anything besides gabrieloc it would give me this error. I think if you switch your name back it will work

**Comment by xTcR** [comment]
Okay thanks!, I will for sure try that when I get home!

**Comment by xTcR** [comment]
Hmm, I changed it all back to gabrieloc and I still get the error, I think it might be something with the WKAppBundleIdentifier where I have to add .watchkit or something but when I add .watchkit it gives another error

**Comment by SpaceBod** [comment]
@TcR go to the WatchKit extension info.plist
And add .watchkit.extension to the end of the identifier
On the WatchKit app add .watchkit
On the iOS one don't add any thing else.
http://stackoverflow.com/questions/30203079/watchkit-extension-bundle-identifiers

**Comment by Spacebod** [comment]
http://stackoverflow.com/questions/30203079/watchkit-extension-bundle-identifiers

**Comment by xTcR** [comment]
Okay thank you, I'll try this when I can and let you know if it works!

**Comment by xTcR** [comment]
Thank you so much @Spacebod it worked! Thank you also to @TheAntboy for trying to help! <3

**Comment by SpaceBod** [comment]
No problem @xTcR
When loading Roms, try use ifunbox as the game roms  seem to cause problems when in a zip format. Though still waiting until it gets further optimised as I can't seem to get past the introduction of Pokémon; just crashes XD

**Comment by xTcR** [comment]
@Spacebod Yeah I'm getting the same with my Apple Watch Series 0 R.I.P., but yeah can't wait for it to be optimized somewhat so I can kinda use it, though there is really no need for it, it is pretty cool to show off :p
