### ISSUE TITLE
May I ask where's the game .gb or .gbc file?

### ISSUE THREAD

**Issue by allenwong** [gabrieloc/GIOVANNI#14]
I checked the project out, installed the app on WatchOS successfully. 
I am gonna to find the game part files, is here anyone leave a tip to help me out find the game files?

**Comment by gabrieloc** [comment]
Sorry, this kind of discussion is illegal.

**Comment by xTcR** [comment]
I don't mean to further this discussion but if do own or have physically purchased the game you are trying to download this is legal but I am just going to assume you have done that, I recommend just googling the game with the word 'rom' after it
