### ISSUE TITLE
Crash When Trying to Load or Save

### ISSUE THREAD

**Issue by xTcR** [gabrieloc/GIOVANNI#19]
Hello!
Recently whilst trying to play Pokemon Yellow on my Apple Watch 42mm Series 0, every time I force touch and tap either the 'Load' or 'Save' button it just crashes the app

**Comment by gabrieloc** [comment]
Can you try building https://github.com/gabrieloc/GIOVANNI/pull/20?

**Comment by xTcR** [comment]
@gabrieloc Will try when I get the chance, thanks

**Comment by spitfire** [comment]
Had the same issue on the same hardware, #20 seems to have fixed crash on save. Unfortunately after load the game [Pokémon Blue (USA, Europe)] just hangs (app is still responsive - I can i.e. go back to game choosing menu). Force touch menu does not work though, so I can't reset the game.
Auto saves/loads seem to be working fine - after sleep/wake cycle the message is displayed and the game is playable.
Additionally I have a question: does the auto save (done automatically on sleep sleep/wake) overwrite manual save (done by force touch)?
