### ISSUE TITLE
Cartridge.cpp and stdfile.h Help

### ISSUE THREAD

**Issue by ronniedee** [gabrieloc/GIOVANNI#2]
Cartridge.cpp Issue

static std::string const stripDir(std::string const &str) {
	std::string::size_type const lastSlash = str.find_last_of('/');
	if (lastSlash != std::string::npos)
		return str.substr(lastSlash + 1);

	return str;
}

std::string const Cartridge::saveBasePath() const {
	return saveDir_.empty()
	     ? defaultSaveBasePath_
	     : saveDir_ + stripDir(defaultSaveBasePath_);
}

void Cartridge::setSaveDir(std::string const &dir) {
	saveDir_ = dir;
	if (!saveDir_.empty() && saveDir_[saveDir_.length() - 1] != '/')
		saveDir_ += '/';
}

static void enforce8bit(unsigned char *data, std::size_t size) {
	if (static_cast<unsigned char>(0x100))
		while (size--)
			*data++ &= 0xFF;

In the while (size--) section, I believe it is line 520, I'm getting a semantic issue stating code will never be executed. I'm totally new to this, so any help would be greatly appreciated! Is there something I'm supposed to add/change? 

stdfile.h Issue

namespace gambatte {

class StdFile : public File {
public:
	explicit StdFile(char const *filename)
	: stream_(filename, std::ios::in | std::ios::binary)
	, fsize_(0)
	{
		if (stream_) {
			stream_.seekg(0, std::ios::end);
			fsize_ = stream_.tellg();
			stream_.seekg(0, std::ios::beg);
		}
	}

I'm also getting an issue here stating:

Implicit conversion loses integer precision: 'streamoff' (aka 'long long') to 'std::size_t' (aka 'unsigned long')

Also not sure what to do. Again, any help would be appreciated! Thanks!

**Comment by gabrieloc** [comment]
Are you getting actual compilation errors or just warnings? You should be able to build and run despite warnings.

Regardless, I just pushed a few changes which fix these exact warnings.
