### ISSUE TITLE
The regions that should be assigned to arrow keys don't seem to work properly

### ISSUE THREAD

**Issue by spitfire** [gabrieloc/GIOVANNI#29]
I can't see any hint on the Watch where are the actual touch targets for UDLR (arrow) keys. When I tap them where they should (roughly) be (according to the image in Readme, they all act like 'A' button. When I swipe right-left/bottom-up (or vice versa) the controls seem to emulate those buttons, but they are way to sensitive to control even Pokemon. I think they used to work on WatchOS3/iOS10.

Currently running https://github.com/gabrieloc/GIOVANNI/commit/87163f69a22321b806dfc4974cc311f3abd3e9eb compiled with Xcode 9.2 on iPhone X running iOS 10.2 and Apple Watch Series 1 running WatchOS 4.2

**Comment by gabrieloc** [comment]
There are no UDLR button controls, only gestures. Feel free to contribute a better solution if you have one :)
