### ISSUE TITLE
uint errors, can't compile

### ISSUE THREAD

**Issue by s95** [gabrieloc/GIOVANNI#3]
![err](https://cloud.githubusercontent.com/assets/25555399/24083367/e6f5af28-0c79-11e7-932f-321ab1499f22.png)

I'm getting these errors in the attached picture using your most recent code. Do you know how I can fix them? I'm running Xcode 8.2.1
-Thank you

**Comment by kyserv** [comment]
Same errors I'm seeing in Xcode 8.3b

**Comment by rheza** [comment]
can confirm 

https://i.imgur.com/saJ34UC.png

**Comment by gabrieloc** [comment]
Giovanni uses a custom version of Gambatte via git submodules. Can you confirm your version is pointing to https://github.com/gabrieloc/gambatte_watchOS/commit/37c775aa1cbf959d11be67165c8dda2ae2c68416 on that repo?

**Comment by s95** [comment]
Great, that worked for me, my version was pointing to a different gambette version. Attached is a picture of what I can see. Do you know if it's possible to add the ROM file to the project so the game can be loaded onto the iPhone simulator? Or would I have to upload it to an actual device through iTunes?
Thanks
![emu](https://cloud.githubusercontent.com/assets/25555399/24134164/69d7d362-0da6-11e7-8e88-c2246df16c3c.png)

**Comment by gabrieloc** [comment]
Pull from `master`, I just pushed a commit which logs the simulator's documents directory at launch. Run the `giovanni` scheme, you'll see the full path in the console, simply move roms to that path on disk.

**Comment by gabrieloc** [comment]
This appears to be addressed so I'll close the issue.

@s95 Take a look at https://github.com/gabrieloc/GIOVANNI/pull/9

**Comment by s95** [comment]
@gabrieloc Yes I got it to work after updating the gambette version, thanks.
