### ISSUE TITLE
A 1024x1024 App Store icon is required for watchOS apps?

### ISSUE THREAD

**Issue by nstumler** [gabrieloc/GIOVANNI#33]
I’ve managed to get the Xcode project on my Mac but now I need a 1024x1024p app icon for it to build correctly. This seems to be the only issue and I’d be happy to get some support if anyone knows what to do or how I can get this icon. Thanks! @gabrieloc

**Comment by nstumler** [comment]
This is what it looks like https://user-images.githubusercontent.com/34840409/35361428-55908390-012f-11e8-8ab3-d06ed443c205.png

**Comment by gabrieloc** [comment]
You're getting a warning. The project is building correctly.

**Comment by nstumler** [comment]
Alright I didn’t know I could still build with a warning. Thanks! @gabrieloc
