### ISSUE TITLE
No sideload with Cydia Impactor?

### ISSUE THREAD

**Issue by ZeiramPP** [gabrieloc/GIOVANNI#7]
I am not sure if i am the problem or something went wrong? I use an IPA file and try to download it with Cydia Impactor, but it is stuck during the varification process in the end. Its not caused due to installation limit and other IPAs work fine, like C64Scene for example? Can anyone help in this case?

**Comment by gabrieloc** [comment]
This project has no affiliation with anything produced by the jailbreak community
