### ISSUE TITLE
Message from debugger: Terminated due to memory issue

### ISSUE THREAD

**Issue by thomasfor** [gabrieloc/GIOVANNI#8]
When running on Apple Watch Series 0 it crashes with memory issue, works fine on the simulator.

**Comment by niccolospa** [comment]
Probably is related to my issue #4

**Comment by gabrieloc** [comment]
Are you on a Series 0 (2015) Apple Watch?

**Comment by niccolospa** [comment]
yes

**Comment by gabrieloc** [comment]
This is a duplicate of https://github.com/gabrieloc/GIOVANNI/issues/4
